#!/usr/bin/perl

use strict;
use NF::RegressLib;
use NF::PacketLib;
use NFUtils::SimplePacket;

use reg_defines_tunneling_openflow_icmp_arp;

use constant NUM_PKTS => 3000;
use constant MAX_LENGTH => 60;
use constant MIN_LENGTH => 60;

my @interfaces = ("nf2c0", "nf2c1", "nf2c2", "nf2c3");
nftest_init(\@ARGV,\@interfaces,);
nftest_start(\@interfaces);

# Put ports into loopback mode
nftest_phy_loopback('nf2c0');
nftest_phy_loopback('nf2c1');
nftest_phy_loopback('nf2c2');
nftest_phy_loopback('nf2c3');

nftest_regread_expect('nf2c0', MDIO_PHY_0_CONTROL_REG(), 0x5140);
nftest_regread_expect('nf2c0', MDIO_PHY_1_CONTROL_REG(), 0x5140);
nftest_regread_expect('nf2c0', MDIO_PHY_2_CONTROL_REG(), 0x5140);
nftest_regread_expect('nf2c0', MDIO_PHY_3_CONTROL_REG(), 0x5140);

`sleep 2`;

nftest_fpga_reset('nf2c0');

#enable encap module on MAC port 0
nftest_regwrite('nf2c0', DECAP_IP_PROTO_REG(),     0xf5);
nftest_regwrite('nf2c0', DECAP_ENABLE_REG(),     0x55);
#nftest_regwrite('nf2c0', DECAP_IP_PROTO_REG(),      0x52);

sub write_entry {
    my ($srcport, $dstport, $row) = @_;

    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_0_REG(), $dstport);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_1_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_2_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_3_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_4_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_5_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_6_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_7_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_8_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_ACTION_9_REG(), 0x0);

    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_0_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_1_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_2_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_3_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_4_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_5_REG(), 0x0);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_6_REG(), $srcport);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_7_REG(), 0x0);

    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_0_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_1_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_2_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_3_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_4_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_5_REG(), 0xFFFFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_6_REG(), 0x00FFFFFF);
    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_CMP_MASK_7_REG(), 0xFFFFFFFF);

    nftest_regwrite('nf2c0', OPENFLOW_WILDCARD_LOOKUP_WRITE_ADDR_REG(), $row);
    }

foreach my $i (0..3) {
    my $dstport = 0x01 << ($i*2);
    my $srcport = ($i*2+1)<<24;
    my $row = $i;
    write_entry($srcport, $dstport, $row);
    }

foreach my $i (0..3) {
    my $dstport = 0x01 << ($i*2+1);
    my $srcport = ($i*2)<<24;
    my $row = $i + 4;
    write_entry($srcport, $dstport, $row);
    }

my @enc_pkt;

$enc_pkt[0] = NFUtils::SimplePacket->new(NFUtils::SimplePacket::PKT_TYPE() => NFUtils::SimplePacket::PKT_TYPE_IP,
                                           NFUtils::SimplePacket::ETH_TYPE() => NFUtils::SimplePacket::ETH_TYPE_IP,
                                           NFUtils::SimplePacket::IP_DST() => 0xeeff0011,
                                           NFUtils::SimplePacket::IP_SRC() => 0xaabbccdd,
                                           NFUtils::SimplePacket::IP_TOS() => 0x0,
                                           NFUtils::SimplePacket::IP_TTL() => 0x25,
		                           NFUtils::SimplePacket::IP_LEN() => 0x56,
		                           NFUtils::SimplePacket::IP_FLAGS_FRAG_OFF() => 0x4000,
                                           NFUtils::SimplePacket::ETH_DST() => '11:22:12:34:56:78',
                                           NFUtils::SimplePacket::ETH_SRC() => '22:33:44:55:66:77',
                                           NFUtils::SimplePacket::IP_PROTO() => 0xf5,
                                           NFUtils::SimplePacket::PKT_LEN() => 38,
                                           NFUtils::SimplePacket::PAYLOAD_GEN() => sub{0});

$enc_pkt[1] = NFUtils::SimplePacket->new(NFUtils::SimplePacket::PKT_TYPE() => NFUtils::SimplePacket::PKT_TYPE_IP,
                                           NFUtils::SimplePacket::ETH_TYPE() => NFUtils::SimplePacket::ETH_TYPE_IP,
                                           NFUtils::SimplePacket::IP_DST() => 0x23456789,
                                           NFUtils::SimplePacket::IP_SRC() => 0xabcdef01,
                                           NFUtils::SimplePacket::IP_TOS() => 0x0,
                                           NFUtils::SimplePacket::IP_TTL() => 0x25,
		                           NFUtils::SimplePacket::IP_LEN() => 0x56,
		                           NFUtils::SimplePacket::IP_FLAGS_FRAG_OFF() => 0x4000,
                                           NFUtils::SimplePacket::ETH_DST() => 'be:ef:12:34:56:78',
                                           NFUtils::SimplePacket::ETH_SRC() => 'de:ad:44:55:66:77',
                                           NFUtils::SimplePacket::IP_PROTO() => 0xf5,
                                           NFUtils::SimplePacket::PKT_LEN() => 38,
                                           NFUtils::SimplePacket::PAYLOAD_GEN() => sub{0});

$enc_pkt[2] = NFUtils::SimplePacket->new(NFUtils::SimplePacket::PKT_TYPE() => NFUtils::SimplePacket::PKT_TYPE_IP,
                                           NFUtils::SimplePacket::ETH_TYPE() => NFUtils::SimplePacket::ETH_TYPE_IP,
                                           NFUtils::SimplePacket::IP_DST() => 0xdeeff001,
                                           NFUtils::SimplePacket::IP_SRC() => 0xcddeeffa,
                                           NFUtils::SimplePacket::IP_TOS() => 0x0,
                                           NFUtils::SimplePacket::IP_TTL() => 0x25,
		                           NFUtils::SimplePacket::IP_LEN() => 0x56,
		                           NFUtils::SimplePacket::IP_FLAGS_FRAG_OFF() => 0x4000,
		                           NFUtils::SimplePacket::ETH_DST() => 'fe:ed:98:76:54:32',
                                           NFUtils::SimplePacket::ETH_SRC() => 'ed:ae:45:67:89:0a',
                                           NFUtils::SimplePacket::IP_PROTO() => 0xf5,
                                           NFUtils::SimplePacket::PKT_LEN() => 38,
                                           NFUtils::SimplePacket::PAYLOAD_GEN() => sub{0});

$enc_pkt[3] = NFUtils::SimplePacket->new(NFUtils::SimplePacket::PKT_TYPE() => NFUtils::SimplePacket::PKT_TYPE_IP,
                                           NFUtils::SimplePacket::ETH_TYPE() => NFUtils::SimplePacket::ETH_TYPE_IP,
                                           NFUtils::SimplePacket::IP_DST() => 0x567beef8,
                                           NFUtils::SimplePacket::IP_SRC() => 0x123feed4,
                                           NFUtils::SimplePacket::IP_TOS() => 0x0,
	                                   NFUtils::SimplePacket::IP_TTL() => 0x25,
		                           NFUtils::SimplePacket::IP_LEN() => 0x56,
		                           NFUtils::SimplePacket::IP_FLAGS_FRAG_OFF() => 0x4000,
                                           NFUtils::SimplePacket::ETH_DST() => 'fe:ad:55:44:33:22',
                                           NFUtils::SimplePacket::ETH_SRC() => 'de:af:99:88:77:66',
                                           NFUtils::SimplePacket::IP_PROTO() => 0xf5,
                                           NFUtils::SimplePacket::PKT_LEN() => 38,
                                           NFUtils::SimplePacket::PAYLOAD_GEN() => sub{0});

# set parameters
my $DA = "00:ca:fe:00:00:01";
my $SA = "aa:bb:cc:dd:ee:ff";
my $TTL = 64;
my $DST_IP = "192.168.1.1";
my $SRC_IP = "192.168.0.1";;
my $nextHopMAC = "dd:55:dd:66:dd:77";

# create mac header
my $MAC_hdr = NF::Ethernet_hdr->new(DA => $DA,
                                     SA => $SA,
                                     Ethertype => 0x800
                                    );

#create IP header
my $IP_hdr = NF::IP_hdr->new(ttl => $TTL,
                              src_ip => $SRC_IP,
                              dst_ip => $DST_IP
                             );

$IP_hdr->checksum(0);  # make sure its zero before we calculate it.
$IP_hdr->checksum($IP_hdr->calc_checksum);

my $num_precreated = 1000;
my $start_val = $MAC_hdr->length_in_bytes() + $IP_hdr->length_in_bytes()+1;

# precreate random sized packets
$MAC_hdr->DA("00:ca:fe:00:00:01");
my @precreated0 = nftest_precreate_ip_pkts($num_precreated, $MAC_hdr, $IP_hdr, MIN_LENGTH, MAX_LENGTH);
$MAC_hdr->DA("00:ca:fe:00:00:02");
my @precreated1 = nftest_precreate_ip_pkts($num_precreated, $MAC_hdr, $IP_hdr, MIN_LENGTH, MAX_LENGTH);
$MAC_hdr->DA("00:ca:fe:00:00:03");
my @precreated2 = nftest_precreate_ip_pkts($num_precreated, $MAC_hdr, $IP_hdr, MIN_LENGTH, MAX_LENGTH);
$MAC_hdr->DA("00:ca:fe:00:00:04");
my @precreated3 = nftest_precreate_ip_pkts($num_precreated, $MAC_hdr, $IP_hdr, MIN_LENGTH, MAX_LENGTH);

print "Sending now: \n";
my $pkt;
my $act_enc_pkt;
my @totalPktLengths = (0, 0, 0, 0);
my @totalPktLengthsEncap = (0, 0, 0, 0);
# send NUM_PKTS packets from ports nf2c0...nf2c3
for(my $i=0; $i<NUM_PKTS; $i++){
  print "$i \r";
  $pkt = $precreated0[int(rand($num_precreated))];
  $act_enc_pkt = $enc_pkt[0]->packed;
  $act_enc_pkt .= $pkt;
  $totalPktLengths[0] += length($pkt);
  $totalPktLengthsEncap[0] += length($pkt) + 38;
  nftest_send('nf2c0', $act_enc_pkt);
  nftest_expect('nf2c0', $pkt);

  $pkt = $precreated1[int(rand($num_precreated))];
  $act_enc_pkt = $enc_pkt[1]->packed;
  $act_enc_pkt .= $pkt;
  $totalPktLengths[1] += length($pkt);
  $totalPktLengthsEncap[1] += length($pkt) + 38; 
  nftest_send('nf2c1', $act_enc_pkt);
  nftest_expect('nf2c1', $pkt);

  $pkt = $precreated2[int(rand($num_precreated))];
  $act_enc_pkt = $enc_pkt[2]->packed;
  $act_enc_pkt .= $pkt;
  $totalPktLengths[2] += length($pkt);
  $totalPktLengthsEncap[2] += length($pkt) + 38; 
  nftest_send('nf2c2', $act_enc_pkt);
  nftest_expect('nf2c2', $pkt);

  $pkt = $precreated3[int(rand($num_precreated))];
  $act_enc_pkt = $enc_pkt[3]->packed;
  $act_enc_pkt .= $pkt;
  $totalPktLengths[3] += length($pkt);
  $totalPktLengthsEncap[3] += length($pkt) + 38; 
  nftest_send('nf2c3', $act_enc_pkt);
  nftest_expect('nf2c3', $pkt);

}

print "\n";

`sleep 2`;

my $unmatched_hoh = nftest_finish();
nftest_reset_phy();

my $total_errors = 0;

print "Checking pkt errors\n";
$total_errors += nftest_print_errors($unmatched_hoh);

# check counter values
for (my $i = 0; $i < 4; $i++) {
        my $reg_data = 0;
        $reg_data = nftest_regread_expect("nf2c0", MAC_GRP_0_RX_QUEUE_NUM_PKTS_STORED_REG() + $i * 0x40000, NUM_PKTS);

        if ($reg_data != NUM_PKTS) {
                $total_errors++;
                print "ERROR: MAC Queue $i counters are wrong\n";
                print "   Rx pkts stored: $reg_data     expected: " . NUM_PKTS . "\n";
        }

        $reg_data = nftest_regread_expect("nf2c0", MAC_GRP_0_TX_QUEUE_NUM_PKTS_SENT_REG() + $i * 0x40000, NUM_PKTS);

        if ($reg_data != NUM_PKTS) {
                $total_errors++;
                print "ERROR: MAC Queue $i counters are wrong\n";
                print "   Tx pkts sent: $reg_data       expected: " . NUM_PKTS . "\n";
        }

        $reg_data = nftest_regread_expect("nf2c0", MAC_GRP_0_RX_QUEUE_NUM_BYTES_PUSHED_REG() + $i * 0x40000, $totalPktLengthsEncap[$i]);

        if ($reg_data != $totalPktLengthsEncap[$i]) {
                $total_errors++;
                print "ERROR: MAC Queue $i counters are wrong\n";
                print "   Rx bytes pushed: $reg_data    expected: " . $totalPktLengthsEncap[$i] . "\n";
        }

        $reg_data = nftest_regread_expect("nf2c0", MAC_GRP_0_TX_QUEUE_NUM_BYTES_PUSHED_REG() + $i * 0x40000, $totalPktLengthsEncap[$i]);

        if ($reg_data != $totalPktLengthsEncap[$i]) {
                $total_errors++;
                print "ERROR: MAC Queue $i counters are wrong\n";
                print "   Tx bytes pushed: $reg_data    expected: " . $totalPktLengthsEncap[$i] . "\n";
        }

        $reg_data = nftest_regread_expect("nf2c0", BRAM_OQ_QUEUE_1_NUM_PKT_BYTES_RECEIVED_REG() + $i * 0x20, $totalPktLengths[$i]);

        if ($reg_data != $totalPktLengths[$i]) {
                $total_errors++;
                print "ERROR: BRAM Queue (DMA) $i counters are wrong\n";
                print "   Rx bytes received: $reg_data    expected: " . $totalPktLengths[$i] . "\n";
        }
}

if ($total_errors==0) {
  print "Test PASSES\n";
  exit 0;
}
else {
  print "Test FAILED: $total_errors errors\n";
  exit 1;
}
